version: '3'

services:
    app:
        build: .
        volumes:
            - .:/app
            - ${HOME}/.composer:/tmp
        ports:
            - ${APP_PORT:-8000}:8000
        command: php artisan serve --host 0.0.0.0 --port 8000
        depends_on:
            - mysql
            - mysqltest
            - mailhog
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - devdata:/var/lib/mysql
    mailhog:
        image: mailhog/mailhog
        ports:
            - 8025:8025
    mysqltest:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_TEST_DATABASE}
            MYSQL_USER: ${DB_TEST_USERNAME}
            MYSQL_PASSWORD: ${DB_TEST_PASSWORD}
        volumes:
            - testdata:/var/lib/mysql

volumes:
    devdata: {}
    testdata: {}
